apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: main
  name: main
spec:
  ports:
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    app: main
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - env:
        - name: Authentication_AzureAd_AADInstance
          value: https://login.microsoftonline.com/
        - name: Authentication_AzureAd_CallbackPath
          value: /auth/response
        - name: Authentication_AzureAd_ClientId
          value: #{Authentication_AzureAd_ClientId}#
        - name: Authentication_AzureAd_ClientSecret
          value: #{Authentication_AzureAd_ClientSecret}#
        - name: Authentication_AzureAd_Domain
          value: microsoft.onmicrosoft.com
        - name: Authentication_AzureAd_GraphResourceId
          value: https://graph.microsoft.com
        - name: Authentication_AzureAd_PostLogoutRedirectUri
          value: #{Authentication_AzureAd_PostLogoutRedirectUri}#
        - name: Authentication_AzureAd_TenantId
          value: #{Authentication_AzureAd_TenantId}#
        - name: Storage_Redis_Configuration
          value: #{Storage_Redis_Configuration}#
        - name: Storage_Redis_InstanceName
          value: #{Storage_Redis_InstanceName}#
        - name: Storage_SqlServer_Kanban_ConnectionString
          value: #{Storage_SqlServer_Kanban_ConnectionString}#
        - name: Storage_SqlServer_Permissions_ConnectionString
          value: #{Storage_SqlServer_Permissions_ConnectionString}#
        - name: Endpoints_ardaapp
          value: #{Endpoints_ardaapp}#
        - name: Endpoints_kanban_service
          value: #{Endpoints_kanban_service}#
        - name: Endpoints_permissions_service
          value: #{Endpoints_permissions_service}#
        - name: Endpoints_reports_service
          value: #{Endpoints_reports_service}#
        - name: KESTREL_LISTEN_KANBAN
          value: http://0.0.0.0:80
        - name: KESTREL_LISTEN_PERMISSIONS
          value: http://0.0.0.0:80
        - name: KESTREL_LISTEN_REPORTS
          value: http://0.0.0.0:80
        - name: certPassword
          value: Pa$$w0rd
        image: visouza/arda.main
        name: main
        ports:
        - containerPort: 443
        - containerPort: 80
        resources: {}
      restartPolicy: Always

